### ISSUE TITLE
File doesn't compiles

### ISSUE THREAD

**Issue by 142ayushkumar** [Jatana/FastOlympicCoding#10]
when i compile a file, it just shows compiling but never compiles.
![image](https://user-images.githubusercontent.com/23264605/47435906-13779a00-d7c3-11e8-90fd-2af5de94a7e3.png)

Console log:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "/home/ayush/.config/sublime-text-3/Packages/FastOlympicCoding/test_manager.py", line 1266, in run
    self.redirect_var_value(var_name, pos=pos)
  File "/home/ayush/.config/sublime-text-3/Packages/FastOlympicCoding/test_manager.py", line 754, in redirect_var_value
    if self.tester.process_manager.has_var_view_api():
AttributeError: 'NoneType' object has no attribute 'process_manager'
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
indexing [job 78]: no files were indexed out of the 1 queued, abandoning crawl
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
[FastOlympicCoding] session saved
indexing [job 168]: no files were indexed out of the 1 queued, abandoning crawl
[FastOlympicCoding] process terminating error
```

**Comment by EternalRights** [comment]
好像无人能解决
