### ISSUE TITLE
compile issue in mac

### ISSUE THREAD

**Issue by madhur1846** [Jatana/FastOlympicCoding#18]
first it is not start when i press cmd + b or ctrl + b (  after pressing cmd + shift + p and then select FastOlympicCoding run side window appear) and just stop at compiling and after press ctrl + ~ it shows 

using gpu buffer for window
Running g++ "/Users/madhurjoshi/Competitive Programming/Competions/e.cpp" -o "/Users/madhurjoshi/Competitive Programming/Competions/e" && "/Users/madhurjoshi/Competitive Programming/Competions/e"
[FastOlympicCoding] session saved
Traceback (most recent call last):
  File "/Users/madhurjoshi/Library/Application Support/Sublime Text 3/Packages/FastOlympicCoding-master/test_manager.py", line 972, in compile
    cmp_data = process_manager.compile()
  File "/Users/madhurjoshi/Library/Application Support/Sublime Text 3/Packages/FastOlympicCoding-master/Modules/ProcessManager.py", line 71, in compile
    cmd = self.get_compile_cmd()
  File "/Users/madhurjoshi/Library/Application Support/Sublime Text 3/Packages/FastOlympicCoding-master/Modules/ProcessManager.py", line 51, in get_compile_cmd
    for x in opt:
TypeError: 'NoneType' object is not iterable
[FastOlympicCoding] process terminating error
[FastOlympicCoding] session saved
Traceback (most recent call last):
  File "/Users/madhurjoshi/Library/Application Support/Sublime Text 3/Packages/FastOlympicCoding-master/test_manager.py", line 972, in compile
    cmp_data = process_manager.compile()
  File "/Users/madhurjoshi/Library/Application Support/Sublime Text 3/Packages/FastOlympicCoding-master/Modules/ProcessManager.py", line 71, in compile
    cmd = self.get_compile_cmd()
  File "/Users/madhurjoshi/Library/Application Support/Sublime Text 3/Packages/FastOlympicCoding-master/Modules/ProcessManager.py", line 51, in get_compile_cmd
    for x in opt:
TypeError: 'NoneType' object is not iterable
Running g++ "/Users/madhurjoshi/Competitive Programming/Competions/e.cpp" -o "/Users/madhurjoshi/Competitive Programming/Competions/e" && "/Users/madhurjoshi/Competitive Programming/Competions/e"
Running g++ "/Users/madhurjoshi/Competitive Programming/Competions/e.cpp" -o "/Users/madhurjoshi/Competitive Programming/Competions/e" && "/Users/madhurjoshi/Competitive Programming/Competions/e"

how to correct it please help sir (and what to chose in build system)

**Comment by npanuhin** [comment]
Please do the following and send the result:

1) Open console <kbd>Ctrl + `</kbd>
2) Paste two commands:
```
sublime.log_commands(True)
sublime.log_input(True)
```
3) Open your file and press <kbd>Ctrl + b</kbd>
4) If the window does not open, press <kbd>Ctrl + Shift + p</kbd> to open the menu and select `FastOlympicCoding: Run`
5) Paste all console data to https://gist.github.com or https://pastebin.com and put a link here

Also, please provide your settings file. I think that you did not change the default settings, so the user part will be enough, however, if you change the default settings - add the default settings file as well. (It will also be great if you put them on **pastebin** or **gist**)

Make sure you press <kbd>Ctrl + b</kbd> while the .cpp (.py, .java) file is open and active.

**Comment by madhur1846** [comment]
> Please do the following and send the result:
> 
> 1. Open console Ctrl + `
> 2. Paste two commands:
> 
> ```
> sublime.log_commands(True)
> sublime.log_input(True)
> ```
> 
> 1. Open your file and press Ctrl + b
> 2. If the window does not open, press Ctrl + Shift + p to open the menu and select `FastOlympicCoding: Run`
> 3. Paste all console data to https://gist.github.com or https://pastebin.com and put a link here
> 
> Also, please provide your settings file (`Tools -> {Cpp}FastOlympicCoding -> settings`). I think that you did not change the default settings, so the user part will be enough, however, if you change the default settings - add the default settings file as well. (It will also be great if you put them on **pastebin** or **gist**)
> 
> Make sure you press Ctrl + b while the .cpp (.py) file is open and active.

i don't know sir how but now its working perfectly. But can u tell  me how can we stop to load all previous test case when we press ctrl + b

**Comment by npanuhin** [comment]
I think the only way to do this is to manually delete all tests.

**Comment by hrushiisenpaii** [comment]
Same problem for me. cmd+b not opening the -run panel. I have to do it by opening menu (cmd+shift+p) then fastolympiccoding: run. Aslo i tried the above method but no progess. Is there anything I can do. I tried reinstalling sublime.

console data after doing the above steps:
command: prompt_open
key evt: super+b
command: build
Running g++ "/Users/hrushikeshpatra/Desktop/cat.cpp" -o "/Users/hrushikeshpatra/Desktop/cat"
command: show_panel {"panel": "console", "toggle": true}
chr evt: s (0x73)
chr evt: u (0x75)
chr evt: b (0x62)
chr evt: l (0x6c)
chr evt: i (0x69)
chr evt: m (0x6d)
chr evt: e (0x65)
chr evt: . (0x2e)
chr evt: l (0x6c)
chr evt: o (0x6f)
chr evt: g (0x67)
chr evt: _ (0x5f)
chr evt: c (0x63)
chr evt: o (0x6f)
chr evt: m (0x6d)
chr evt: m (0x6d)
chr evt: a (0x61)
chr evt: n (0x6e)
chr evt: d (0x64)
chr evt: s (0x73)
chr evt: ( (0x28)
chr evt: ) (0x29)
key evt: left
key evt: left
command: move {"by": "characters", "forward": false}
chr evt: T (0x54)
chr evt: r (0x72)
chr evt: u (0x75)
chr evt: e (0x65)
key evt: right
key evt: right
command: move {"by": "characters", "forward": true}
>>> sublime.log_commands(True)
chr evt: s (0x73)
chr evt: u (0x75)
chr evt: b (0x62)
chr evt: l (0x6c)
chr evt: i (0x69)
chr evt: m (0x6d)
chr evt: e (0x65)
chr evt: . (0x2e)
chr evt: l (0x6c)
chr evt: o (0x6f)
chr evt: g (0x67)
chr evt: _ (0x5f)
chr evt: i (0x69)
chr evt: n (0x6e)
chr evt: p (0x70)
chr evt: u (0x75)
chr evt: t (0x74)
chr evt: ( (0x28)
chr evt: ) (0x29)
key evt: left
key evt: left
command: move {"by": "characters", "forward": false}
chr evt: T (0x54)
chr evt: r (0x72)
chr evt: u (0x75)
chr evt: e (0x65)
>>> sublime.log_input(True)
command: drag_select {"event": {"button": 1, "x": 355.8125, "y": 367.1484375}}
key evt: super+b
command: build
Running g++ "/Users/hrushikeshpatra/Desktop/cat.cpp" -o "/Users/hrushikeshpatra/Desktop/cat"
key evt: shift+super+p
command: show_overlay {"overlay": "command_palette"}
chr evt: f (0x66)
chr evt: a (0x61)
chr evt: s (0x73)
chr evt: t (0x74)
[FastOlympicCoding] session saved
command: show_panel {"panel": "console", "toggle": true}
key evt: super+a
command: select_all
command: drag_select {"event": {"button": 1, "x": 231.140625, "y": 491.65625}}
command: drag_select {"event": {"button": 1, "x": 810.78515625, "y": 586.69140625}}
