### ISSUE TITLE
I can keep typing in the input, and the output doesnt show.

### ISSUE THREAD

**Issue by jyheo98** [Jatana/FastOlympicCoding#23]
![image](https://user-images.githubusercontent.com/67140978/95040451-a7bc3c80-070e-11eb-9ff0-4b1d59c36235.png)

I really don't know the computeristic stuff just except problem solving,
and I really want to use this thing.

Can you help me fix this? I can keep typing in the input. It doesnt end.

**Comment by Jatana** [comment]
Hi!

Press ctrl+~, try to run it again, and send the log information here.

**Comment by jyheo98** [comment]
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/허준영/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/허준영/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/허준영/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.122336
warning: mnemonic R not found in menu caption FastOlympicCoding
first paint time: 0.206336
startup time: 0.229336
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin CppFastOlympicCoding.ContestHandler
reloading plugin CppFastOlympicCoding.Cpp_Intellij_Sense
reloading plugin CppFastOlympicCoding.NumberSpliter
reloading plugin CppFastOlympicCoding.olympic_funcs
reloading plugin CppFastOlympicCoding.settings
reloading plugin CppFastOlympicCoding.stress_manager
reloading plugin CppFastOlympicCoding.test_edit
reloading plugin CppFastOlympicCoding.test_manager
plugins loaded
Running g++ "C:\Users\허준영\Desktop\PS\Problem_solving.cpp" -o "C:\Users\허준영\Desktop\PS/Problem_solving" && "C:\Users\허준영\Desktop\PS/Problem_solving"
Package Control: No updated packages
warning: mnemonic R not found in menu caption FastOlympicCoding
[FastOlympicCoding] session saved

Thanks.

**Comment by jyheo98** [comment]
Ok. I fixed it. Sublime text doesnt support UTF-8, so I think the "허준영" in my file directory ruined the program. I made a new account with english, and it is working perfectly. Thanks 👍

**Comment by stiff** [comment]
I have similar issue but for different reason:

```
AttributeError: 'NoneType' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 743, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "~/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/olympic_funcs.py", line 128, in on_text_command
    ext = path.splitext(view.file_name())[1][1:]
  File "./python3.3/posixpath.py", line 125, in splitext
  File "./python3.3/genericpath.py", line 92, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by Jatana** [comment]
Hi @stiff,

Could you attach the full log?

Also, have you selected the view with the cpp file before running your program?

**Comment by stiff** [comment]
I believe it's all that was there.

Sure I had the file open. I installed plugin, restarted Sublime, opened some solution from random contest, and wanted to figure out how to reproduce the amazing things from video in the README, but didn't succeed. Since then I didn't have time to figure out what's the problem and this issue looked similar to me so decided just to put it here, maybe someone will get an idea how to fix it.

**Comment by Jatana** [comment]
Have your program compiled or it stuck with "compiling" title?

**Comment by Ajay2908** [comment]
Hi Jatana, I have an issue while parsing contests on codeforces it doesn't show any output and keeps waiting 
![Screenshot (212)](https://user-images.githubusercontent.com/74947404/100267826-146aef00-2f7a-11eb-9577-06f780820c03.png)

**Comment by npanuhin** [comment]
Hello, @Ajay2908.
This happens because you haven't inserted another newline after the test case. I tried to run your code and got the same result when I inserted `2\n2\n5` instead of `2\n2\n5\n`. So be careful with line endings - there must be another one :)

**Comment by Ajay2908** [comment]
yeah the parser itself isnt fetching that last \n  so I myself added a \n in  codeforces.py code and it worked :)

**Comment by coder-mohit** [comment]
i cant give outuput in my program
my log is 
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/user/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/user/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/user/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.124431
warning: mnemonic R not found in menu caption FastOlympicCoding
startup time: 0.195431
first paint time: 0.201431
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin CppFastOlympicCoding.ContestHandler
reloading plugin CppFastOlympicCoding.Cpp_Intellij_Sense
reloading plugin CppFastOlympicCoding.NumberSpliter
reloading plugin CppFastOlympicCoding.olympic_funcs
reloading plugin CppFastOlympicCoding.settings
reloading plugin CppFastOlympicCoding.stress_manager
reloading plugin CppFastOlympicCoding.test_edit
reloading plugin CppFastOlympicCoding.test_manager
plugins loaded
[FastOlympicCoding] session saved
Package Control: Skipping automatic upgrade, last run at 2021-03-22 10:01:01, next run at 2021-03-22 11:01:01 or after
reloading /C/Users/user/OneDrive/Desktop/coding/sol.cpp
reloading /C/Users/user/OneDrive/Desktop/coding/output.txt
[FastOlympicCoding] session saved
reloading /C/Users/user/OneDrive/Desktop/coding/sol.cpp
reloading /C/Users/user/OneDrive/Desktop/coding/output.txt

**Comment by Rye1st** [comment]
@stiff @Jatana  I have the same question as you, but I know why. This program works if you try to enter numbers without using the keypad, but I believe this is a bug and hope the creators can fix it.

**Comment by jihadmia35** [comment]
![Screenshot from 2024-07-12 04-18-55](https://github.com/user-attachments/assets/57d54513-27a5-4388-9877-f1f29ef04e54)
same here
