### ISSUE TITLE
Breaks when having runtime error.

### ISSUE THREAD

**Issue by shurongwang** [Jatana/FastOlympicCoding#8]
the plug-in breaks down if there is error at runtime. Therefore I have to restart the editor again.

**Comment by Jatana** [comment]
This is the common error for Sublime Text 3 on the OS X platform. Plugin hosts child process crash cause plugin host crash. The standard run tool crashes too.

It has appeared in the latest builds. So, I think this problem will be fixed.

But, everything works fine and do not crashes with debugger(lldb).
So, to install lldb you can install xcode, I recommend xcode **9.4.1** version.
You can download it from here - https://developer.apple.com/download/more

And then just press ctrl+shift+b to launch a program with lldb.

**Comment by Jatana** [comment]
Press ctrl+~ and write here the log.

**Comment by ShurongWang** [comment]
Nothing in the console qwq.
![image](https://user-images.githubusercontent.com/22816399/46579224-98328c00-ca3f-11e8-8129-42613f0ff84e.png)

**Comment by ShurongWang** [comment]
```[FastOlympicCoding] session saved
Traceback (most recent call last):
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/test_manager.py", line 300, in go
    self.insert_test()
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/test_manager.py", line 278, in insert_test
    self.process_manager.run()
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/debuggers/DebugodPy3Ejector.py", line 140, in run
    self.__listen()
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/debuggers/DebugodPy3Ejector.py", line 56, in __listen
    s = self.read()
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/debuggers/DebugodPy3Ejector.py", line 148, in read
    out = self.interact('_.get_output()')
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/debuggers/DebugodPy3Ejector.py", line 52, in interact
    proc_dbg.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Jatana** [comment]
Make sure your xcode version is 9.4.1 and it is location is /Applications/Xcode.app/

**Comment by Jatana** [comment]
I have changed something. Update plugin, restart Sublime and try it again.

**Comment by ShurongWang** [comment]
```
[FastOlympicCoding] session saved
Traceback (most recent call last):
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/test_manager.py", line 966, in compile
    cmp_data = process_manager.compile()
  File "/Users/shurongwang/Library/Application Support/Sublime Text 3/Packages/CppFastOlympicCoding/debuggers/DebugodPy3Ejector.py", line 136, in compile
    return eval(self.interact('_.compile()'))
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by ShurongWang** [comment]
great, it works. Thanks a lot.

**Comment by FallenParadise** [comment]
Hello, I installed your plugin via Package ControlI. I also installed Xcode and Python, but still have problem with 'compiling' and I have the console log as the last one. So, what can I do?
