### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 11: invalid continuation byte

### ISSUE THREAD

**Issue by OY9R** [Jatana/FastOlympicCoding#80]
When I save a cpp file. 
```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Sublime Text\Packages\CppFastOlympicCoding\Cpp_Intellij_Sense.py", line 65, in sense_timer
    self.insert_error_marks()
  File "C:\Users\username\AppData\Roaming\Sublime Text\Packages\CppFastOlympicCoding\Cpp_Intellij_Sense.py", line 165, in insert_error_marks
    s = process.communicate()[0].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 11: invalid continuation byte
```

**Comment by OY9R** [comment]
C:\Users\中文\AppData\Roaming\Sublime Text\Packages\CppFastOlympicCoding\Cpp_Intellij_Sense.py
Don't use chiese on username!
